version: 2

sources:
  - name: raw_customers_src
    schema: dbt_dataset
    tables:
      - name: raw_customers
        description: "Source table containing raw customer data"
        columns:
          - name: id
            description: "Unique identifier for customers"
            tests:
              - unique
              - not_null

models:
  - name: my_first_dbt_model
    description: "Model that transforms raw customer data into a curated table"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "Another example model for learning dbt"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
